version: "3.9"
services:
  backend:
    # build:
    #   dockerfile: Dockerfile
    image: mcoblefiasmw/arm32v7_buster
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - /dev:/dev
      # - /opt/vc:/opt/vc
      - ./src:/src
    environment:
      - DISPLAY=$DISPLAY
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
    command: python3 /src/main.py
    # command: tail -F nothing
    privileged: true
